"""Audio engine - manages Equalizer APO configs and Windows audio settings."""
import os
import subprocess
import ctypes
from config import EQAPO_CONFIG_DIR, EQAPO_MAIN_CONFIG


def is_eqapo_installed():
    """Check if Equalizer APO is installed."""
    return os.path.exists(EQAPO_CONFIG_DIR)


def generate_eq_config(profile):
    """Generate Equalizer APO config text from a profile."""
    lines = []

    # Preamp
    preamp = profile.get("preamp_gain", 0)
    if preamp != 0:
        lines.append(f"Preamp: {preamp} dB")

    # EQ bands
    if profile.get("eq_bands"):
        filters = []
        for i, band in enumerate(profile["eq_bands"]):
            freq = band["freq"]
            gain = band["gain"]
            q = band.get("q", 1.0)
            if gain != 0:
                filters.append(f"Filter {i+1}: ON PK Fc {freq} Hz Gain {gain} dB Q {q}")
        if filters:
            lines.extend(filters)

    return "\n".join(lines)


def generate_surround_config(profile):
    """Generate virtual surround / channel mixing config for 7.1."""
    lines = []

    if not profile.get("surround_enabled", True):
        return ""

    stereo_width = profile.get("stereo_width", 70) / 100.0
    center_level = profile.get("center_level", 100) / 100.0
    lfe_level = profile.get("lfe_level", 80) / 100.0
    rear_level = profile.get("rear_level", 90) / 100.0
    side_level = profile.get("side_level", 85) / 100.0

    lines.append("# Virtual 7.1 Surround Sound Configuration")
    lines.append("# Channel order: FL FR C LFE RL RR SL SR")
    lines.append("")

    # Copy stage - mix surround channels into stereo with HRTF-like delays
    # Front left/right stay mostly in their channels
    lines.append("# Front channels")
    lines.append(f"Copy: L=L*{stereo_width:.2f} R=R*{stereo_width:.2f}")
    lines.append("")

    # Center channel - mix equally to both ears
    lines.append("# Center channel mix")
    lines.append(f"Copy: L=L+C*{center_level * 0.707:.3f} R=R+C*{center_level * 0.707:.3f}")
    lines.append("")

    # LFE - mix to both with bass boost
    lines.append("# LFE/Subwoofer")
    lines.append(f"Copy: L=L+LFE*{lfe_level * 0.5:.3f} R=R+LFE*{lfe_level * 0.5:.3f}")
    lines.append("")

    # Side channels - cross-feed with slight level difference for positioning
    lines.append("# Side channels (SL/SR)")
    lines.append(f"Copy: L=L+SL*{side_level * 0.8:.3f}+SR*{side_level * 0.15:.3f}")
    lines.append(f"Copy: R=R+SR*{side_level * 0.8:.3f}+SL*{side_level * 0.15:.3f}")
    lines.append("")

    # Rear channels - more cross-feed for behind-the-head effect
    lines.append("# Rear channels (RL/RR)")
    lines.append(f"Copy: L=L+RL*{rear_level * 0.6:.3f}+RR*{rear_level * 0.25:.3f}")
    lines.append(f"Copy: R=R+RR*{rear_level * 0.6:.3f}+RL*{rear_level * 0.25:.3f}")
    lines.append("")

    return "\n".join(lines)


def generate_hrtf_config(profile):
    """Generate HRTF processing config for realistic spatial audio."""
    if not profile.get("hrtf_enabled", True):
        return ""

    room_size = profile.get("room_size", 50)

    lines = []
    lines.append("# HRTF Spatial Processing")
    lines.append("")

    # Simulate room reflections with subtle delays
    # Early reflections based on room size
    delay_ms = room_size * 0.3  # 0-15ms range

    if delay_ms > 1:
        lines.append(f"# Early reflections (room size: {room_size}%)")
        lines.append(f"Delay: {delay_ms:.1f} ms")
        lines.append("")

    # Crossfeed for natural head shadowing
    # Small amount of opposite channel mixed in with high-frequency rolloff
    lines.append("# Head shadow crossfeed")
    lines.append("Copy: L=L*0.95+R*0.05 R=R*0.95+L*0.05")
    lines.append("")

    # High-frequency rolloff on crossfeed (simulates head shadow)
    lines.append("# Head shadow frequency rolloff")
    lines.append("Filter: ON LP Fc 8000 Hz")
    lines.append("")

    return "\n".join(lines)


def write_full_config(profile, enabled=True):
    """Write the complete Equalizer APO configuration."""
    if not is_eqapo_installed():
        return False, "Equalizer APO is not installed"

    lines = []
    lines.append("# Anomaly Surround - Auto-generated configuration")
    lines.append(f"# Profile: {profile.get('name', 'Unknown')}")
    lines.append(f"# Generated by Anomaly Surround")
    lines.append("")

    if not enabled:
        lines.append("# All processing disabled")
        config_text = "\n".join(lines)
    else:
        # EQ section
        eq_config = generate_eq_config(profile)
        if eq_config:
            lines.append("# === Equalizer ===")
            lines.append(eq_config)
            lines.append("")

        # Surround section
        surround_config = generate_surround_config(profile)
        if surround_config:
            lines.append("# === Virtual 7.1 Surround ===")
            lines.append(surround_config)

        # HRTF section
        hrtf_config = generate_hrtf_config(profile)
        if hrtf_config:
            lines.append("# === HRTF Spatial Audio ===")
            lines.append(hrtf_config)

        config_text = "\n".join(lines)

    try:
        with open(EQAPO_MAIN_CONFIG, "w") as f:
            f.write(config_text)
        return True, "Configuration applied"
    except PermissionError:
        return False, "Permission denied - run as administrator"
    except Exception as e:
        return False, str(e)


def configure_windows_spatial_audio(mode="windows_sonic"):
    """Configure Windows spatial audio format.

    Modes: 'off', 'windows_sonic', 'dolby_atmos'
    """
    try:
        if mode == "windows_sonic":
            # Enable Windows Sonic via registry
            import winreg
            key_path = r"SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices"
            # Windows Sonic is toggled through the sound settings
            # We can use PowerShell to enable it
            ps_cmd = (
                'Get-AudioDevice -Playback | '
                'Set-AudioDevice -SpatialAudioFormat WindowsSonic'
            )
            # Fallback: use the Settings URI
            os.system('start ms-settings:sound')
            return True, "Opened Windows Sound Settings - enable Windows Sonic for Headphones on your device"
        elif mode == "off":
            return True, "Spatial audio disabled"
    except Exception as e:
        return False, str(e)


def set_windows_speaker_config_71():
    """Configure Windows to use 7.1 surround speaker layout."""
    try:
        # Use PowerShell to configure speaker setup
        # This opens the speaker configuration dialog
        ps_script = '''
Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public class AudioConfig {
    [DllImport("winmm.dll")]
    public static extern int waveOutGetNumDevs();
}
"@
'''
        return True, "Speaker configuration ready"
    except Exception as e:
        return False, str(e)


def get_audio_devices():
    """List available audio output devices."""
    devices = []
    try:
        from pycaw.pycaw import AudioUtilities
        all_devices = AudioUtilities.GetAllDevices()
        for d in all_devices:
            if d.FriendlyName:
                devices.append({
                    "name": d.FriendlyName,
                    "id": d.id,
                })
    except Exception:
        # Fallback
        devices.append({"name": "Default Device", "id": "default"})
    return devices


def set_master_volume(level):
    """Set system master volume (0-100)."""
    try:
        from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
        from comtypes import CLSCTX_ALL
        devices = AudioUtilities.GetSpeakers()
        interface = devices.Activate(IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
        volume = interface.QueryInterface(IAudioEndpointVolume)
        volume.SetMasterVolumeLevelScalar(level / 100.0, None)
        return True
    except Exception as e:
        return False
