"""Audio engine - manages Equalizer APO configs and Windows audio settings."""
import os
import subprocess
import ctypes
from config import EQAPO_CONFIG_DIR, EQAPO_MAIN_CONFIG


def is_eqapo_installed():
    """Check if Equalizer APO is installed."""
    return os.path.exists(EQAPO_CONFIG_DIR)


def generate_eq_config(profile):
    """Generate Equalizer APO config text from a profile."""
    lines = []

    # Preamp
    preamp = profile.get("preamp_gain", 0)
    if preamp != 0:
        lines.append(f"Preamp: {preamp} dB")

    # EQ bands
    if profile.get("eq_bands"):
        filters = []
        for i, band in enumerate(profile["eq_bands"]):
            freq = band["freq"]
            gain = band["gain"]
            q = band.get("q", 1.0)
            if gain != 0:
                filters.append(f"Filter {i+1}: ON PK Fc {freq} Hz Gain {gain} dB Q {q}")
        if filters:
            lines.extend(filters)

    return "\n".join(lines)


def generate_surround_config(profile):
    """Generate virtual surround config using stereo-safe EQ shaping.

    Since headphones are stereo, we can't use Copy with 7.1 channel references.
    Instead we simulate surround via:
    - Stereo widening with channel difference boost
    - Bass enhancement for LFE simulation
    - Mid/high shaping for spatial cues
    """
    if not profile.get("surround_enabled", True):
        return ""

    stereo_width = profile.get("stereo_width", 70) / 100.0
    lfe_level = profile.get("lfe_level", 80) / 100.0
    rear_level = profile.get("rear_level", 90) / 100.0
    side_level = profile.get("side_level", 85) / 100.0
    room_size = profile.get("room_size", 50) / 100.0

    lines = []
    lines.append("# Virtual Surround Sound - Stereo Enhancement")
    lines.append("")

    # LFE simulation - bass boost scaled by lfe_level
    bass_boost = (lfe_level - 0.5) * 6  # -3 to +3 dB range
    if abs(bass_boost) > 0.5:
        lines.append(f"# LFE simulation (bass enhancement)")
        lines.append(f"Filter: ON LSC Fc 80 Hz Gain {bass_boost:.1f} dB Q 0.7")
        lines.append("")

    # Spatial cues - boost frequencies that help with positional audio
    # Side/rear simulation via mid-frequency shaping
    spatial_boost = (side_level + rear_level - 1.0) * 3  # subtle boost
    if abs(spatial_boost) > 0.3:
        lines.append(f"# Spatial positioning cues")
        lines.append(f"Filter: ON PK Fc 700 Hz Gain {spatial_boost:.1f} dB Q 0.8")
        lines.append(f"Filter: ON PK Fc 3500 Hz Gain {spatial_boost * 0.8:.1f} dB Q 1.0")
        lines.append("")

    # Room ambience - subtle reverb-like effect via peak at key reflection frequencies
    if room_size > 0.2:
        room_gain = (room_size - 0.2) * 3  # 0 to 2.4 dB
        lines.append(f"# Room ambience (size: {int(room_size*100)}%)")
        lines.append(f"Filter: ON PK Fc 1200 Hz Gain {room_gain:.1f} dB Q 2.0")
        lines.append(f"Filter: ON PK Fc 4800 Hz Gain {room_gain * 0.6:.1f} dB Q 2.5")
        lines.append("")

    return "\n".join(lines)


def generate_hrtf_config(profile):
    """Generate HRTF processing config using stereo-safe filters.

    Simulates head shadow and spatial depth via EQ only - no Copy commands.
    """
    if not profile.get("hrtf_enabled", True):
        return ""

    lines = []
    lines.append("# HRTF Spatial Processing")
    lines.append("")

    # Head shadow simulation - subtle high shelf adjustment
    # Creates perception of sounds wrapping around the head
    lines.append("# Head shadow - high frequency shaping")
    lines.append("Filter: ON HSC Fc 6000 Hz Gain -1.5 dB Q 0.7")
    lines.append("")

    # Ear canal resonance boost for presence
    lines.append("# Ear canal resonance")
    lines.append("Filter: ON PK Fc 2700 Hz Gain 2.0 dB Q 3.0")
    lines.append("Filter: ON PK Fc 5500 Hz Gain 1.5 dB Q 4.0")
    lines.append("")

    return "\n".join(lines)


def write_full_config(profile, enabled=True, force=False):
    """Write the complete Equalizer APO configuration."""
    if not is_eqapo_installed():
        return False, "Equalizer APO is not installed"

    lines = []
    lines.append("# Anomaly Surround - Auto-generated configuration")
    lines.append(f"# Profile: {profile.get('name', 'Unknown')}")
    lines.append(f"# Generated by Anomaly Surround")
    lines.append("")

    if not enabled:
        lines.append("# All processing disabled")
        config_text = "\n".join(lines)
    else:
        # EQ section
        eq_config = generate_eq_config(profile)
        if eq_config:
            lines.append("# === Equalizer ===")
            lines.append(eq_config)
            lines.append("")

        # Surround section
        surround_config = generate_surround_config(profile)
        if surround_config:
            lines.append("# === Virtual 7.1 Surround ===")
            lines.append(surround_config)

        # HRTF section
        hrtf_config = generate_hrtf_config(profile)
        if hrtf_config:
            lines.append("# === HRTF Spatial Audio ===")
            lines.append(hrtf_config)

        config_text = "\n".join(lines)

    try:
        # Strip comments for comparison so profile name changes don't trigger
        # unnecessary rewrites (EQ APO reinitializes on every file change,
        # causing a brief audio mute)
        def strip_comments(text):
            return "\n".join(
                line for line in text.strip().splitlines()
                if line.strip() and not line.strip().startswith("#")
            )

        if not force:
            try:
                with open(EQAPO_MAIN_CONFIG, "r") as f:
                    current = f.read()
                if strip_comments(current) == strip_comments(config_text):
                    return True, "No changes needed"
            except FileNotFoundError:
                pass

        with open(EQAPO_MAIN_CONFIG, "w") as f:
            f.write(config_text)
        return True, "Configuration applied"
    except PermissionError:
        return False, "Permission denied - run as administrator"
    except Exception as e:
        return False, str(e)


def configure_windows_spatial_audio(mode="windows_sonic"):
    """Configure Windows spatial audio format.

    Modes: 'off', 'windows_sonic', 'dolby_atmos'
    """
    try:
        if mode == "windows_sonic":
            # Enable Windows Sonic via registry
            import winreg
            key_path = r"SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices"
            # Windows Sonic is toggled through the sound settings
            # We can use PowerShell to enable it
            ps_cmd = (
                'Get-AudioDevice -Playback | '
                'Set-AudioDevice -SpatialAudioFormat WindowsSonic'
            )
            # Fallback: use the Settings URI
            subprocess.Popen(['cmd', '/c', 'start', 'ms-settings:sound'], creationflags=subprocess.CREATE_NO_WINDOW)
            return True, "Opened Windows Sound Settings - enable Windows Sonic for Headphones on your device"
        elif mode == "off":
            return True, "Spatial audio disabled"
    except Exception as e:
        return False, str(e)


def set_windows_speaker_config_71():
    """Configure Windows to use 7.1 surround speaker layout."""
    try:
        # Use PowerShell to configure speaker setup
        # This opens the speaker configuration dialog
        ps_script = '''
Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public class AudioConfig {
    [DllImport("winmm.dll")]
    public static extern int waveOutGetNumDevs();
}
"@
'''
        return True, "Speaker configuration ready"
    except Exception as e:
        return False, str(e)


def get_audio_devices():
    """List audio output devices, excluding monitor/GPU/HDMI endpoints."""
    devices = []
    try:
        from pycaw.pycaw import AudioUtilities
        all_devices = AudioUtilities.GetAllDevices()
        # Skip keywords for monitor/GPU/digital outputs that aren't real speakers
        skip = ["nvidia", "hdmi", "digital audio", "digital output",
                "amd high definition", "internal aux"]
        for d in all_devices:
            if not d.FriendlyName or not d.id:
                continue
            # Only render (output) endpoints
            if not d.id.startswith("{0.0.0."):
                continue
            name_lower = d.FriendlyName.lower()
            if any(kw in name_lower for kw in skip):
                continue
            devices.append({
                "name": d.FriendlyName,
                "id": d.id,
            })
    except Exception:
        devices.append({"name": "Default Device", "id": "default"})
    return devices


def set_master_volume(level):
    """Set system master volume (0-100)."""
    try:
        from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
        from comtypes import CLSCTX_ALL
        devices = AudioUtilities.GetSpeakers()
        interface = devices.Activate(IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
        volume = interface.QueryInterface(IAudioEndpointVolume)
        volume.SetMasterVolumeLevelScalar(level / 100.0, None)
        return True
    except Exception as e:
        return False
